/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as VerifyRequiredImport } from './routes/verify-required'
import { Route as VerifyEmailImport } from './routes/verify-email'
import { Route as VerifyBvnImport } from './routes/verify-bvn'
import { Route as ProfileImport } from './routes/profile'
import { Route as LoginImport } from './routes/login'
import { Route as LeaderboardImport } from './routes/leaderboard'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as CommunityImport } from './routes/community'
import { Route as AdminImport } from './routes/admin'
import { Route as IndexImport } from './routes/index'
import { Route as VaultIdImport } from './routes/vault.$id'
import { Route as ShareVaultIdImport } from './routes/share.$vaultId'
import { Route as InviteVaultIdImport } from './routes/invite.$vaultId'
import { Route as AuthCallbackImport } from './routes/auth.callback'
import { Route as AdminSettingsImport } from './routes/admin.settings'
import { Route as AdminUsersUserIdImport } from './routes/admin.users.$userId'
import { Route as AdminTxTxIdImport } from './routes/admin.tx.$txId'
import { Route as AdminAuditAuditIdImport } from './routes/admin.audit.$auditId'

// Create/Update Routes

const VerifyRequiredRoute = VerifyRequiredImport.update({
  id: '/verify-required',
  path: '/verify-required',
  getParentRoute: () => rootRoute,
} as any)

const VerifyEmailRoute = VerifyEmailImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRoute,
} as any)

const VerifyBvnRoute = VerifyBvnImport.update({
  id: '/verify-bvn',
  path: '/verify-bvn',
  getParentRoute: () => rootRoute,
} as any)

const ProfileRoute = ProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LeaderboardRoute = LeaderboardImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const CommunityRoute = CommunityImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const VaultIdRoute = VaultIdImport.update({
  id: '/vault/$id',
  path: '/vault/$id',
  getParentRoute: () => rootRoute,
} as any)

const ShareVaultIdRoute = ShareVaultIdImport.update({
  id: '/share/$vaultId',
  path: '/share/$vaultId',
  getParentRoute: () => rootRoute,
} as any)

const InviteVaultIdRoute = InviteVaultIdImport.update({
  id: '/invite/$vaultId',
  path: '/invite/$vaultId',
  getParentRoute: () => rootRoute,
} as any)

const AuthCallbackRoute = AuthCallbackImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRoute,
} as any)

const AdminSettingsRoute = AdminSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)

const AdminUsersUserIdRoute = AdminUsersUserIdImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)

const AdminTxTxIdRoute = AdminTxTxIdImport.update({
  id: '/tx/$txId',
  path: '/tx/$txId',
  getParentRoute: () => AdminRoute,
} as any)

const AdminAuditAuditIdRoute = AdminAuditAuditIdImport.update({
  id: '/audit/$auditId',
  path: '/audit/$auditId',
  getParentRoute: () => AdminRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/verify-bvn': {
      id: '/verify-bvn'
      path: '/verify-bvn'
      fullPath: '/verify-bvn'
      preLoaderRoute: typeof VerifyBvnImport
      parentRoute: typeof rootRoute
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailImport
      parentRoute: typeof rootRoute
    }
    '/verify-required': {
      id: '/verify-required'
      path: '/verify-required'
      fullPath: '/verify-required'
      preLoaderRoute: typeof VerifyRequiredImport
      parentRoute: typeof rootRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsImport
      parentRoute: typeof AdminImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackImport
      parentRoute: typeof rootRoute
    }
    '/invite/$vaultId': {
      id: '/invite/$vaultId'
      path: '/invite/$vaultId'
      fullPath: '/invite/$vaultId'
      preLoaderRoute: typeof InviteVaultIdImport
      parentRoute: typeof rootRoute
    }
    '/share/$vaultId': {
      id: '/share/$vaultId'
      path: '/share/$vaultId'
      fullPath: '/share/$vaultId'
      preLoaderRoute: typeof ShareVaultIdImport
      parentRoute: typeof rootRoute
    }
    '/vault/$id': {
      id: '/vault/$id'
      path: '/vault/$id'
      fullPath: '/vault/$id'
      preLoaderRoute: typeof VaultIdImport
      parentRoute: typeof rootRoute
    }
    '/admin/audit/$auditId': {
      id: '/admin/audit/$auditId'
      path: '/audit/$auditId'
      fullPath: '/admin/audit/$auditId'
      preLoaderRoute: typeof AdminAuditAuditIdImport
      parentRoute: typeof AdminImport
    }
    '/admin/tx/$txId': {
      id: '/admin/tx/$txId'
      path: '/tx/$txId'
      fullPath: '/admin/tx/$txId'
      preLoaderRoute: typeof AdminTxTxIdImport
      parentRoute: typeof AdminImport
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdImport
      parentRoute: typeof AdminImport
    }
  }
}

// Create and export the route tree

interface AdminRouteChildren {
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminAuditAuditIdRoute: typeof AdminAuditAuditIdRoute
  AdminTxTxIdRoute: typeof AdminTxTxIdRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSettingsRoute: AdminSettingsRoute,
  AdminAuditAuditIdRoute: AdminAuditAuditIdRoute,
  AdminTxTxIdRoute: AdminTxTxIdRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/verify-bvn': typeof VerifyBvnRoute
  '/verify-email': typeof VerifyEmailRoute
  '/verify-required': typeof VerifyRequiredRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/invite/$vaultId': typeof InviteVaultIdRoute
  '/share/$vaultId': typeof ShareVaultIdRoute
  '/vault/$id': typeof VaultIdRoute
  '/admin/audit/$auditId': typeof AdminAuditAuditIdRoute
  '/admin/tx/$txId': typeof AdminTxTxIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/verify-bvn': typeof VerifyBvnRoute
  '/verify-email': typeof VerifyEmailRoute
  '/verify-required': typeof VerifyRequiredRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/invite/$vaultId': typeof InviteVaultIdRoute
  '/share/$vaultId': typeof ShareVaultIdRoute
  '/vault/$id': typeof VaultIdRoute
  '/admin/audit/$auditId': typeof AdminAuditAuditIdRoute
  '/admin/tx/$txId': typeof AdminTxTxIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/verify-bvn': typeof VerifyBvnRoute
  '/verify-email': typeof VerifyEmailRoute
  '/verify-required': typeof VerifyRequiredRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/invite/$vaultId': typeof InviteVaultIdRoute
  '/share/$vaultId': typeof ShareVaultIdRoute
  '/vault/$id': typeof VaultIdRoute
  '/admin/audit/$auditId': typeof AdminAuditAuditIdRoute
  '/admin/tx/$txId': typeof AdminTxTxIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/community'
    | '/dashboard'
    | '/leaderboard'
    | '/login'
    | '/profile'
    | '/verify-bvn'
    | '/verify-email'
    | '/verify-required'
    | '/admin/settings'
    | '/auth/callback'
    | '/invite/$vaultId'
    | '/share/$vaultId'
    | '/vault/$id'
    | '/admin/audit/$auditId'
    | '/admin/tx/$txId'
    | '/admin/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/community'
    | '/dashboard'
    | '/leaderboard'
    | '/login'
    | '/profile'
    | '/verify-bvn'
    | '/verify-email'
    | '/verify-required'
    | '/admin/settings'
    | '/auth/callback'
    | '/invite/$vaultId'
    | '/share/$vaultId'
    | '/vault/$id'
    | '/admin/audit/$auditId'
    | '/admin/tx/$txId'
    | '/admin/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/community'
    | '/dashboard'
    | '/leaderboard'
    | '/login'
    | '/profile'
    | '/verify-bvn'
    | '/verify-email'
    | '/verify-required'
    | '/admin/settings'
    | '/auth/callback'
    | '/invite/$vaultId'
    | '/share/$vaultId'
    | '/vault/$id'
    | '/admin/audit/$auditId'
    | '/admin/tx/$txId'
    | '/admin/users/$userId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CommunityRoute: typeof CommunityRoute
  DashboardRoute: typeof DashboardRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  VerifyBvnRoute: typeof VerifyBvnRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  VerifyRequiredRoute: typeof VerifyRequiredRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  InviteVaultIdRoute: typeof InviteVaultIdRoute
  ShareVaultIdRoute: typeof ShareVaultIdRoute
  VaultIdRoute: typeof VaultIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CommunityRoute: CommunityRoute,
  DashboardRoute: DashboardRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  VerifyBvnRoute: VerifyBvnRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  VerifyRequiredRoute: VerifyRequiredRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  InviteVaultIdRoute: InviteVaultIdRoute,
  ShareVaultIdRoute: ShareVaultIdRoute,
  VaultIdRoute: VaultIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/community",
        "/dashboard",
        "/leaderboard",
        "/login",
        "/profile",
        "/verify-bvn",
        "/verify-email",
        "/verify-required",
        "/auth/callback",
        "/invite/$vaultId",
        "/share/$vaultId",
        "/vault/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin": {
      "filePath": "admin.tsx",
      "children": [
        "/admin/settings",
        "/admin/audit/$auditId",
        "/admin/tx/$txId",
        "/admin/users/$userId"
      ]
    },
    "/community": {
      "filePath": "community.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/leaderboard": {
      "filePath": "leaderboard.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/verify-bvn": {
      "filePath": "verify-bvn.tsx"
    },
    "/verify-email": {
      "filePath": "verify-email.tsx"
    },
    "/verify-required": {
      "filePath": "verify-required.tsx"
    },
    "/admin/settings": {
      "filePath": "admin.settings.tsx",
      "parent": "/admin"
    },
    "/auth/callback": {
      "filePath": "auth.callback.tsx"
    },
    "/invite/$vaultId": {
      "filePath": "invite.$vaultId.tsx"
    },
    "/share/$vaultId": {
      "filePath": "share.$vaultId.tsx"
    },
    "/vault/$id": {
      "filePath": "vault.$id.tsx"
    },
    "/admin/audit/$auditId": {
      "filePath": "admin.audit.$auditId.tsx",
      "parent": "/admin"
    },
    "/admin/tx/$txId": {
      "filePath": "admin.tx.$txId.tsx",
      "parent": "/admin"
    },
    "/admin/users/$userId": {
      "filePath": "admin.users.$userId.tsx",
      "parent": "/admin"
    }
  }
}
ROUTE_MANIFEST_END */
